map_update_interval: 2.0
maxRange: 10.0
maxUrange: 2.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.1
ogain: 3.0
lskip: 0
minimumScore: 800
srr: 0.01
srt: 0.02
str: 0.01
stt: 0.02
linearUpdate: 0.5
angularUpdate: 0.436
temporalUpdate: -1.0
resampleThreshold: 0.5
particles: 60
delta: 0.01
xmin: -4.0
xmax:  4.0
ymin: -4.0
ymax:  4.0
